title: "Aditya Muttagi"
description: "Product & Data Analytics"

theme: minima

author: "Aditya Muttagi"
email: "your.email@example.com" # replace

header_pages:
  - about.md
  - projects.md
  - resume.md
  - contact.md

minima:
  skin: dark
  social_links:
    - platform: github
      user_url: "https://github.com/aditya-muttagi"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/your-handle/"
